import { getDataSource } from "@/db/data-source";
import {
  AdAccount,
  AiRecommendation,
  Alert,
  AuditLog,
  AutomationRule,
  CampaignGoal,
  CampaignMetricSnapshot,
  CampaignTemplate,
  Client,
  ClientGoal,
  ClientMetaSettings,
  ClientTag,
  CreativeAsset,
  LookalikeJob,
  MetaAdAccountInventory,
  MetaAuth,
  MetaAudienceCache,
  MetaBusiness,
  MetaPage,
  MetricSnapshot,
  NotificationState,
  SavedView,
  SyncQueueJob,
  SyncRun,
  Tenant,
  TenantSyncState,
  User,
  UserClient
} from "@/db/entities/registry";

export async function repositories() {
  const ds = await getDataSource();
  return {
    tenant: ds.getRepository(Tenant),
    user: ds.getRepository(User),
    client: ds.getRepository(Client),
    adAccount: ds.getRepository(AdAccount),
    metaAuth: ds.getRepository(MetaAuth),
    metaBusiness: ds.getRepository(MetaBusiness),
    metaPage: ds.getRepository(MetaPage),
    metaAdAccountInventory: ds.getRepository(MetaAdAccountInventory),
    metricSnapshot: ds.getRepository(MetricSnapshot),
    campaignMetricSnapshot: ds.getRepository(CampaignMetricSnapshot),
    clientGoal: ds.getRepository(ClientGoal),
    campaignGoal: ds.getRepository(CampaignGoal),
    alert: ds.getRepository(Alert),
    aiRecommendation: ds.getRepository(AiRecommendation),
    auditLog: ds.getRepository(AuditLog),
    notificationState: ds.getRepository(NotificationState),
    clientMetaSettings: ds.getRepository(ClientMetaSettings),
    syncRun: ds.getRepository(SyncRun),
    syncQueueJob: ds.getRepository(SyncQueueJob),
    tenantSyncState: ds.getRepository(TenantSyncState),
    savedView: ds.getRepository(SavedView),
    clientTag: ds.getRepository(ClientTag),
    metaAudienceCache: ds.getRepository(MetaAudienceCache),
    lookalikeJob: ds.getRepository(LookalikeJob),
    campaignTemplate: ds.getRepository(CampaignTemplate),
    creativeAsset: ds.getRepository(CreativeAsset),
    automationRule: ds.getRepository(AutomationRule),
    userClient: ds.getRepository(UserClient)
  };
}
