import createIntlMiddleware from "next-intl/middleware";
import NextAuth from "next-auth";
import { NextResponse } from "next/server";

import { authConfig } from "@/auth.config";
import { routing } from "@/i18n/routing";
import { getLocaleFromPath, stripLocale } from "@/lib/locale";
import { isPublicApiPath, isPublicPath } from "@/lib/public-routes";

const intlMiddleware = createIntlMiddleware(routing);
const { auth } = NextAuth(authConfig);

function sessionHasEmail(auth: { user?: { email?: string | null } } | null) {
  const email = auth?.user?.email;
  return typeof email === "string" && email.length > 0;
}

const STATIC_PUBLIC_FILE = /\.(?:png|jpe?g|gif|svg|webp|ico|woff2?|ttf|eot|mp4|webm|pdf)$/i;

// Next.js metadata-route filenames (auto-generated by src/app/icon.tsx, manifest.ts, robots.ts,
// sitemap.ts & friends) live at the root, outside [locale] — they must bypass the locale
// middleware or it 404s them under /pt-BR/… (and crawlers need robots.txt/sitemap.xml without auth).
const METADATA_ROUTE = /^\/(icon|apple-icon|opengraph-image|twitter-image|manifest\.webmanifest|sitemap\.xml|robots\.txt)$/;

const FRIENDLY_LANDING_PATHS: Record<string, { pt: string; en: string }> = {
  "/cockpit": { pt: "/pt-BR/cockpit", en: "/en/cockpit" },
  "/relatorios": { pt: "/pt-BR/relatorios", en: "/en/relatorios" },
  "/reports": { pt: "/pt-BR/relatorios", en: "/en/relatorios" },
  "/criativos": { pt: "/pt-BR/criativos", en: "/en/criativos" },
  "/creatives": { pt: "/pt-BR/criativos", en: "/en/criativos" }
};

function preferredLandingLanguage(req: Request): "pt" | "en" {
  const country = req.headers.get("x-vercel-ip-country")?.toUpperCase();
  if (country) return country === "BR" ? "pt" : "en";
  return req.headers.get("accept-language")?.toLowerCase().includes("pt") ? "pt" : "en";
}

export default auth((req) => {
  const isLoggedIn = sessionHasEmail(req.auth);
  const path = req.nextUrl.pathname;

  // URLs públicas de campanha ficam sem prefixo de idioma. Na Vercel, o país decide:
  // Brasil recebe pt-BR; os demais países recebem inglês. O rewrite é interno, então
  // `/cockpit` continua limpo na barra do navegador.
  const friendlyLanding = FRIENDLY_LANDING_PATHS[path];
  if (friendlyLanding) {
    const host = req.headers.get("host") ?? req.headers.get("x-forwarded-host") ?? req.nextUrl.host;
    const protocol = req.headers.get("x-forwarded-proto") ?? req.nextUrl.protocol.replace(":", "");
    const destination = new URL(
      `${friendlyLanding[preferredLandingLanguage(req)]}${req.nextUrl.search}`,
      `${protocol}://${host}`
    );
    return NextResponse.rewrite(destination);
  }

  // Public folder assets must bypass auth + locale middleware or <img src="/…"> 404s.
  if (path.startsWith("/brand/") || STATIC_PUBLIC_FILE.test(path) || METADATA_ROUTE.test(path)) {
    return NextResponse.next();
  }

  if (path.startsWith("/api")) {
    if (!isLoggedIn && !isPublicApiPath(path)) {
      return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
    }
    return NextResponse.next();
  }

  const locale = getLocaleFromPath(path);
  const pathWithoutLocale = stripLocale(path);

  const isPublic = isPublicPath(pathWithoutLocale);

  if (!isLoggedIn && !isPublic) {
    const login = new URL(`/${locale}/login`, req.nextUrl.origin);
    // Preserva a query string (ex.: ?plan=X) — sem isso, o usuário volta pro checkout depois do
    // login sem o plano selecionado.
    login.searchParams.set("callbackUrl", path + req.nextUrl.search);
    return NextResponse.redirect(login);
  }

  // A landing ("/") é pública e acessível mesmo logado (sem auto-redirect).
  // Só a página de login manda o usuário logado pro app.
  if (isLoggedIn && pathWithoutLocale === "/login") {
    const switchAccount = req.nextUrl.searchParams.get("switch") === "1";
    if (!switchAccount) {
      return NextResponse.redirect(new URL(`/${locale}/dashboard`, req.nextUrl.origin));
    }
  }

  return intlMiddleware(req);
});

export const config = {
  // Exclude large video upload — middleware body buffering truncates multipart payloads.
  matcher: [
    "/((?!_next/static|_next/image|_next/webpack-hmr|favicon.ico|brand/|.*\\.(?:png|jpe?g|gif|svg|webp|ico|woff2?|ttf|eot|mp4|webm|pdf)$|api/creative-assets/video).*)"
  ]
};
